### ISSUE TITLE
searchbar makes counter look more ugly on mobile

### ISSUE THREAD

**Issue by username-is-required** [Tanza3D/reddark#33]
it doesn’t look like there’s any padding so there’s no space between the searchbar and the count, and because the count is forced onto two lines it breaks when scrolling down (and part of the search bar is cut off as well).

screenshots attached below

![IMG_9302](https://github.com/Tanza3D/reddark/assets/136007111/4f6dd7e0-fe7f-4cb1-a5e8-fb8787a8fc8a)
![IMG_9303](https://github.com/Tanza3D/reddark/assets/136007111/5ebe6043-4c5d-4f3a-9705-2873d566087b)

**Comment by Tanza3D** [comment]
i hate phones so much

**Comment by Tanza3D** [comment]
fixed probably

**Comment by username-is-required** [comment]
fyi this still happens when scrolling

![IMG_9304](https://github.com/Tanza3D/reddark/assets/136007111/a64ceefa-04d2-450f-b517-e6719fbf9194)
